/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCombobox: typeof import('./src/admin/components/forms/AppCombobox.vue')['default']
    AppDropzone: typeof import('./src/admin/components/forms/AppDropzone.vue')['default']
    AppSelect2: typeof import('./src/admin/components/forms/AppSelect2.vue')['default']
    AppTextArea: typeof import('./src/admin/components/forms/AppTextArea.vue')['default']
    AppTextField: typeof import('./src/admin/components/forms/AppTextField.vue')['default']
    AppTinyEditor: typeof import('./src/admin/components/forms/AppTinyEditor.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/admin/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/admin/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/admin/@core/components/cards/CardStatisticsWithImages.vue')['default']
    MoreBtn: typeof import('./src/admin/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/admin/@core/components/ThemeSwitcher.vue')['default']
  }
}

// For TSX support
declare global {
  const AppCombobox: typeof import('./src/admin/components/forms/AppCombobox.vue')['default']
  const AppDropzone: typeof import('./src/admin/components/forms/AppDropzone.vue')['default']
  const AppSelect2: typeof import('./src/admin/components/forms/AppSelect2.vue')['default']
  const AppTextArea: typeof import('./src/admin/components/forms/AppTextArea.vue')['default']
  const AppTextField: typeof import('./src/admin/components/forms/AppTextField.vue')['default']
  const AppTinyEditor: typeof import('./src/admin/components/forms/AppTinyEditor.vue')['default']
  const CardStatisticsHorizontal: typeof import('./src/admin/@core/components/cards/CardStatisticsHorizontal.vue')['default']
  const CardStatisticsVertical: typeof import('./src/admin/@core/components/cards/CardStatisticsVertical.vue')['default']
  const CardStatisticsWithImages: typeof import('./src/admin/@core/components/cards/CardStatisticsWithImages.vue')['default']
  const MoreBtn: typeof import('./src/admin/@core/components/MoreBtn.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ThemeSwitcher: typeof import('./src/admin/@core/components/ThemeSwitcher.vue')['default']
}